### PR TITLE
Testing branch with changes to readme.

### PR DESCRIPTION
**Pull request by stefcenti2022**
Merging changes to readme and Resources.

### CODE REVIEW

**Review by stefcenti2022 — COMMENTED** [review]
Ready to commit.

**Comment by stefcenti2022** [comment]
Testing pushing to main with restrictions set to require 1 review and blocking merge.

**Comment by stefcenti2022** [comment]
Testing Squash and merge

**Comment by stefcenti2022** [comment]
testing

**Comment by stefcenti2022** [comment]
testing Merge pull request

**Comment by stefcenti2022** [comment]
Testing merge pull request

**Comment by stefcenti2022** [comment]
testing merge pull request after allowing forced merging to everyone

**Review by Handeneilan — APPROVED** [review]
Testing review request, "it looks good to me"

**Comment by stefcenti2022** [comment]
Added architecture diagram to readme to test git branching, pull request, approval, merge and commit.

**Pull request merged**
